# Generated by Django 4.2 on 2023-05-25 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient_Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PatientName', models.CharField(max_length=20)),
                ('PatientPhoneNumber', models.CharField(max_length=10)),
                ('PatientEmail', models.EmailField(max_length=254)),
                ('PatientGender', models.CharField(max_length=10)),
                ('PatientAge', models.IntegerField()),
                ('PatientPassword', models.CharField(max_length=10)),
            ],
        ),
    ]
