# Generated by Django 4.2 on 2023-05-27 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_patientloginform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient_registration',
            old_name='PatientPassword',
            new_name='Patient_Password',
        ),
        migrations.RenameField(
            model_name='patient_registration',
            old_name='PatientPhoneNumber',
            new_name='Patient_PhoneNumber',
        ),
    ]
