# Generated by Django 4.2 on 2023-05-30 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_patient_registration_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient_registration',
            name='user',
        ),
    ]
