# Generated by Django 4.2 on 2023-05-30 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0008_patient_registration_patient_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient_registration',
            name='Patient_Address',
        ),
        migrations.RemoveField(
            model_name='patient_registration',
            name='Patient_Age',
        ),
        migrations.RemoveField(
            model_name='patient_registration',
            name='Patient_Email',
        ),
        migrations.RemoveField(
            model_name='patient_registration',
            name='Patient_Gender',
        ),
        migrations.RemoveField(
            model_name='patient_registration',
            name='Patient_Name',
        ),
        migrations.RemoveField(
            model_name='patient_registration',
            name='Patient_Password',
        ),
        migrations.RemoveField(
            model_name='patient_registration',
            name='Patient_PhoneNumber',
        ),
    ]
