# Generated by Django 4.2 on 2023-05-31 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0010_patient_registration_patient_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient_registration',
            name='Patient_Address',
        ),
    ]
