# Generated by Django 4.2 on 2023-05-31 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0013_patient_registration_patient_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Patient_Registration',
        ),
        migrations.DeleteModel(
            name='PatientLoginForm',
        ),
    ]
