# Generated by Django 4.2 on 2023-05-31 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0016_patient_registration_patient_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient_registration',
            name='id',
        ),
        migrations.AlterField(
            model_name='patient_registration',
            name='Patient_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
