# Generated by Django 4.2 on 2023-06-01 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0017_remove_patient_registration_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient_registration',
            name='Patient_id',
        ),
        migrations.AddField(
            model_name='patient_registration',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
