# Generated by Django 4.2 on 2023-05-25 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorregistrationdetails',
            old_name='Email_id',
            new_name='Doctor_Clinic_Address',
        ),
        migrations.RenameField(
            model_name='doctorregistrationdetails',
            old_name='Phone_Number',
            new_name='Doctor_Email_id',
        ),
        migrations.RemoveField(
            model_name='doctorregistrationdetails',
            name='City',
        ),
        migrations.AddField(
            model_name='doctorregistrationdetails',
            name='Doctor_Phone_Number',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
