# Generated by Django 4.2 on 2023-05-25 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_rename_email_id_doctorregistrationdetails_doctor_clinic_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorregistrationdetails',
            name='Doctor_Specialization',
            field=models.CharField(default='', max_length=10),
        ),
    ]
