# Generated by Django 4.2 on 2023-05-27 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_doctorregistrationdetails_doctor_specialization'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorLoginForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DoctorPhoneNumber', models.CharField(max_length=20)),
                ('DoctorPassword', models.CharField(max_length=100)),
            ],
        ),
    ]
