# Generated by Django 4.2 on 2023-05-29 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_appointmentbookingform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentbookingform',
            name='Doctor_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='appointmentbookingform',
            name='Patient_id',
            field=models.CharField(max_length=20),
        ),
    ]
