# Generated by Django 4.2 on 2023-05-30 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0007_doctorregistrationdetails_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorregistrationdetails',
            name='user',
        ),
    ]
