# Generated by Django 4.2 on 2023-05-30 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0008_remove_doctorregistrationdetails_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentbookingform',
            name='Doctor_id',
            field=models.IntegerField(max_length=20),
        ),
        migrations.AlterField(
            model_name='appointmentbookingform',
            name='Patient_id',
            field=models.IntegerField(max_length=20),
        ),
    ]
