# Generated by Django 4.2 on 2023-05-31 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0010_alter_doctorregistrationdetails_doctor_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentbookingform',
            name='Doctor_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='appointmentbookingform',
            name='Patient_id',
            field=models.IntegerField(),
        ),
    ]
