# Generated by Django 4.2 on 2023-05-31 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0011_alter_appointmentbookingform_doctor_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='appointmentBookingForm',
        ),
        migrations.DeleteModel(
            name='DoctorLoginForm',
        ),
        migrations.DeleteModel(
            name='DoctorRegistrationdetails',
        ),
    ]
