# Generated by Django 4.2 on 2023-05-31 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0012_delete_appointmentbookingform_delete_doctorloginform_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='appointmentBookingForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Doctor_id', models.IntegerField()),
                ('Patient_id', models.IntegerField()),
                ('Doctor_Name', models.CharField(max_length=20)),
                ('Appointment_Name', models.CharField(max_length=20)),
                ('Appointment_Number', models.CharField(max_length=100)),
                ('Appointment_Age', models.CharField(max_length=100)),
                ('Appointment_Gender', models.CharField(max_length=100)),
                ('Appointment_Description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorLoginForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DoctorPhoneNumber', models.CharField(max_length=20)),
                ('DoctorPassword', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorRegistrationdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Doctor_Name', models.CharField(default='', max_length=1000)),
                ('Doctor_Phone_Number', models.IntegerField()),
                ('Doctor_Email_id', models.EmailField(max_length=254)),
                ('Doctor_Clinic_Address', models.CharField(default='', max_length=10)),
                ('Clinic_Name', models.CharField(default='', max_length=10)),
                ('Doctor_Specialization', models.CharField(default='', max_length=10)),
                ('Password', models.CharField(default='', max_length=10)),
                ('Confirm_Password', models.CharField(default='', max_length=10)),
            ],
        ),
    ]
