# Generated by Django 4.2 on 2023-06-01 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0014_remove_appointmentbookingform_appointment_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentbookingform',
            name='Patient_id',
        ),
    ]
