# Generated by Django 4.2 on 2023-06-01 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0015_remove_appointmentbookingform_patient_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointmentbookingform',
            old_name='Appintment_Email',
            new_name='Appintment_Gender',
        ),
    ]
