# Generated by Django 4.2 on 2023-06-01 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0016_rename_appintment_email_appointmentbookingform_appintment_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentbookingform',
            name='Appintment_Gender',
            field=models.CharField(max_length=100),
        ),
    ]
