# Generated by Django 4.2 on 2023-06-01 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0017_alter_appointmentbookingform_appintment_gender'),
    ]

    operations = [
        
    ]
