# Generated by Django 4.2 on 2023-06-01 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0018_appointmentbookingform_appointment_date_and_more'),
    ]

    operations = [
  
    ]
