# Generated by Django 4.2 on 2023-06-01 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0019_remove_appointmentbookingform_appointment_time'),
    ]

    operations = [
     
    ]
