# Generated by Django 4.2 on 2023-06-01 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0020_alter_appointmentbookingform_appointment_date'),
    ]

    operations = [
     
    ]
